# .cog.toml
packages = ["chart-a", "chart-b"]

[workspace]
changelog_path = "CHANGELOG.md"
tag_prefix = "{package}-v"

[package.chart-a]
path = "charts/chart-a"
version_file = "charts/chart-a/Chart.yaml"
version_regex = '^version:\s*(?P<version>\d+\.\d+\.\d+)'
version_replace = 'version: {{version}}'
changelog_path = "charts/chart-a/CHANGELOG.md"

[package.chart-b]
path = "charts/chart-b"
version_file = "charts/chart-b/Chart.yaml"
version_regex = '^version:\s*(?P<version>\d+\.\d+\.\d+)'
version_replace = 'version: {{version}}'
changelog_path = "charts/chart-b/CHANGELOG.md"

