#tag_prefix = "{package}-"

pre_package_bump_hooks = [
  """
    pwd
    """,
]

[packages]
chart-a = { path = "charts/chart-a", changelog_path = "charts/chart-a/CHANGELOG.md" }
chart-b = { path = "charts/chart-b", changelog_path = "charts/chart-b/CHANGELOG.md" }
