#generate_mono_repository_package_tags = true
tag_prefix = "{package}-"

[packages.chart-a]
path = "charts/chart-a"
changelog_path = "charts/chart-a/CHANGELOG.md"
post_bump_hooks = ["scripts/update_chart_yaml.sh chart-a {{version}}"]

[packages.chart-b]
path = "charts/chart-b"
changelog_path = "charts/chart-b/CHANGELOG.md"
post_bump_hooks = ["scripts/update_chart_yaml.sh chart-b {{version}}"]

